### ISSUE TITLE
Is there easy to live replicate a running multilevel server?

### ISSUE THREAD

**Issue by matiu** [juliangruber/multilevel#67]
We have a production multilevel server and we would like to have a live replica, standing by (not need for the replica to receive outside request, just replicate and stand by).

Is is possible to do this? Thanks a lot.

**Comment by juliangruber** [comment]
multilevel itself doesn't have to do anything with replication, it's just a client library. There's modules for replicating a leveldb that you can use, and still use multilevel. Check for example level-2pc, level-master, level-replicate and more

**Comment by matiu** [comment]
Thanks a lot for the quick response.

I thought that multilevel hold the lock of the levelDB, so no other process
(like https://github.com/hij1nx/level-2pc)  should access it.  I will give
it a try.
thanks.



On Wed, Apr 8, 2015 at 10:53 AM, Julian Gruber <notifications@github.com>
wrote:

> Closed #67 <https://github.com/juliangruber/multilevel/issues/67>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliangruber/multilevel/issues/67#event-276248816>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!
