### ISSUE TITLE
[Error: write after end]

### ISSUE THREAD

**Issue by kumavis** [juliangruber/multilevel#69]
server sends 'close' after transport emits 'finish' causing `write after end`

* transport emits finish
* [Error: write after end]
* server emits close

**Comment by juliangruber** [comment]
can you create a gist demonstrating this problem? or can you at least show how you're hooking up multilevel with the connections?

**Comment by juliangruber** [comment]
can you create a gist demonstrating this problem? or can you at least show how you're hooking up multilevel with the connections?

**Comment by kumavis** [comment]
yeah should have with the original issue
but now i can't seem to reproduce.
I was using websocket-stream but have since peeled back to just tcp.
if I hit it again I'll reopen
