### ISSUE TITLE
Errors while accessing read-stream are not propagated

### ISSUE THREAD

**Issue by domachine** [juliangruber/multilevel#78]
Take the following access method:

```js
...
  access: function() {
    throw new Error('unauthorized');
  }
...
```

Now get a read-stream on the client:

```js
db.createReadStream()
  .on('error', err => console.log(err));
```

What I expect now, is that the event handler is called. Instead nothing happens and the stream stays open. Is this a bug or am I doing something wrong? How is error handling in this situation supposed to be done?

**Comment by domachine** [comment]
Closing this in favor of #75, sorry

**Comment by domachine** [comment]
Ups ... just noticed, this is actually a different problem

**Comment by juliangruber** [comment]
hey, thanks for reporting! you can speed up the process of getting this fixed by creating a gist that contains all code necessary to reproduce this problem

**Comment by domachine** [comment]
Hi, here comes the gist.

What I expect here is, that the error handler of the read-stream is called.

https://gist.github.com/domachine/c757b396d5e69da7d221

**Comment by juliangruber** [comment]
fixed in 7.2.2

**Comment by ralphtheninja** [comment]
:+1:

**Comment by domachine** [comment]
Awesome! :+1:
