### ISSUE TITLE
If the database is read and write, close the window will go wrong

### ISSUE THREAD

**Issue by milu2003** [juliangruber/multilevel#88]
Error as follows:

`Uncaught Exception:
Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)`

How to solve it

**Comment by juliangruber** [comment]
are you getting this error on the server?

**Comment by milu2003** [comment]
I don't know what you mean.
err show on the renderer page

**Comment by milu2003** [comment]
I guess that is, a lot of asynchronous read and write is still in, forced termination of the error

Must have a mechanism to close the window, cut off the client and server connection

**Comment by milu2003** [comment]
I think the reasons may be too many concurrent. If the frequent read and write database, the program directly crashes. So I suggest using bagpipe to control concurrency
